services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    network_mode: host

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

networks:
  monitoring: